services:
  - type: web
    name: rag-research-paper-assistant-frontend
    rootDir: frontend
    runtime: node
    buildCommand: |
      npm install
      npm install -g serve
      npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://rag-based-research-paper-assistant.onrender.com
      - key: NODE_VERSION
        value: 18.17.0

  - type: web
    name: rag-research-paper-assistant
    rootDir: .
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: rag-based-research-paper-assistant-v4
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
      - key: DATABASE_URL
        fromDatabase:
          name: rag-research-paper-db-v4
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.9

databases:
  - name: rag-research-paper-db-v4
    databaseName: rag_research_paper_db_v4
    user: rag_research_paper_db_v4_user